resource_rules:
  issues:
    rules:
      - name: Close old "needinfo" policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 1
          state: opened
          labels:
            - needinfo
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This issue is now closed due to being marked as "needinfo" with no updates for a long time. Please re-open it if still relevant.
            CC {{assignees}}

      - name: Close old "waiting for feedback" policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 1
          state: opened
          labels:
            - waiting for feedback
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This issue is now closed due to being marked as "waiting for feedback" with no updates for a long time. Please re-open it if still relevant.
            CC {{assignees}}

      - name: Close old "needs attention" policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 2
          state: opened
          labels:
            - needs attention
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This issue is now closed due to being marked as "needs attention" with no updates for a long time. Please re-open it if still relevant.
            CC {{assignees}}
      
      - name: Unlabelled after 8 days
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 8
          state: opened
          no_additional_labels: true
        limits:
          most_recent: 50
        actions:
          labels:
            - needs attention
          comment: |
            {{author}} This issue has gone unlabelled for 8 days. It needs somone to label it.
          summarize:
            title: |
              #{resource[:type].capitalize} require labels
            item: |
              - [ ] [{{title}}]({{web_url}}) {{labels}}
            redact_confidential_resources: false
            summary: |
              The following issues require labels:

              {{items}}

              Please take care of them.

              /label ~"needs attention"


  merge_requests:
    rules:
      - name: Close old "WIP" policy
        conditions:
          title: WIP
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 4
          state: opened
          no_additional_labels: true
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This merge request was closed due to being marked as "work in progress" with no updates for a very long time. Please re-open it if interested in finishing it. :)
            CC {{assignees}}
