.Dd July 29, 2018
.Dt gnome-session-remmina 1
.Os
.Sh NAME
.Nm gnome-session-remmina
.Nd GNOME Shell session script for Remmina
.Sh DESCRIPTION
.Nm
This script is part of the Remmina kiosk mode.
If you have a freedesktop compliant Login Manager, a Remmina kiosk mode will be
added in the list of available sessions.
.Sh SEE ALSO
.Xr remmina 1
.Sh AUTHORS
.An Antenore Gatta Aq Mt antenore@simbiosi.org
