.Dd August 30, 2019
.Dt remmina-file-wrapper 1
.Os Linux
.Sh NAME
.Nm remmina-file-wrapper
.Sh SYNOPSIS
.Nm
.Op Ar protocol:///file
.Op Ar remmina options
.Sh DESCRIPTION
Wrapper script to execute Remmina with protocol handlers.
.Sh SEE ALSO
.Xr remmina 1
.Sh AUTHORS
.An Antenore Gatta Aq Mt antenore@simbiosi.org
