.TH remmina 1 2009-12-12 "remmina"
.SH NAME
remmina \- remote desktop client for GNOME desktop environment
.SH SYNOPSIS
.B remmina
.SH DESCRIPTION
Remmina is a remote desktop connection client able to display and control a
remote desktop session. It can connect to a VNC platform as well as windows
terminal servers.
.SH AUTHORS
Remmina was written by Vic Lee <llyzs@163.com>
.PP
This manual page was written by Luca Falavigna <dktrkranz@debian.org>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.
.PP
On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL-2'
