name: remmina
adopt-info: remmina
version: git
version-script: cat snap/SNAP_VERSION || echo echo +git$(git rev-parse --short HEAD)
icon: data/desktop/scalable/apps/org.remmina.Remmina.svg
description: |
  Remmina is a remote desktop client written in GTK+, aiming to be useful for
  system administrators and travellers, who need to work with lots of remote
  computers in front of either large monitors or tiny netbooks. Remmina supports
  multiple network protocols in an integrated and consistent user interface.
  Currently RDP, VNC, SPICE, NX, XDMCP and SSH are supported.

  Remmina is free and open-source software, released under GNU GPL license.

grade: stable
confinement: strict

parts:
  freerdp:
    plugin: cmake
    source: https://github.com/FreeRDP/FreeRDP.git
    source-depth: 1
    build-packages:
      - build-essential
      - libasound2-dev
      - libavcodec-dev
      - libavutil-dev
      - libcups2-dev
      - libffi-dev
      - libgnutls-dev
      - libgnutls28-dev
      - libnacl-dev
      - libjpeg-dev
      - libpcsclite-dev
      - libpulse-dev
      - libsecret-1-dev
      - libssl-dev
      - libx11-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbfile-dev
      - libxml2-dev
      - libxrandr-dev
      - libxtst-dev
      - libxv-dev
      - libavresample-dev
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_WAYLAND=on
      - -DWITH_CLIENT=off
      - -DWITH_SERVER=off
      - -DWITH_PULSE=on
      - -DWITH_GSTREAMER=off
      - -DWITH_FFMPEG=on
      - -DWITH_CHANNELS=on
      - -DSTATIC_CHANNELS=off
      - -DWITH_CUPS=on
      - -DWITH_PCSC=on
      - -DWITH_JPEG=on

    # XXX: This is an hack to have a kind of bind-mount with absolute prefix.
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    organize:
      snap/remmina/current: .

    prime:
      - -usr/include
      - -usr/lib/cmake
      - -usr/lib/pkgconfig

  # Remove this (and use again libssh-dev) once libssh-0.8 is available in distro
  libssh-0.8:
    plugin: cmake
    source: "https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.8.0.tar.gz"
    configflags:
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DWITH_GSSAPI=ON
      - -DWITH_NACL=0
      - -DWITH_EXAMPLES:BOOL=OFF

    # XXX: This is an hack to have a kind of bind-mount with absolute prefix.
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    organize:
      snap/remmina/current: .

    prime:
      - ./**/libssh*.so.*

  remmina:
    plugin: cmake
    source: .
    parse-info: [usr/share/metainfo/org.remmina.Remmina.appdata.xml]
    override-pull: |
      snapcraftctl pull
      SNAPCRAFT_PART_SRC=$SNAPCRAFT_PART_INSTALL/../src
      cp -av $SNAPCRAFT_STAGE/../snap $SNAPCRAFT_PART_SRC
    stage-packages:
      - xauth
    build-packages:
      - intltool
      - libappindicator3-dev
      - libavahi-ui-gtk3-dev
      - libgcrypt20-dev
      - libgnome-keyring-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsoup2.4-dev
      - libspice-client-gtk-3.0-dev
      - libspice-protocol-dev
      - libvncserver-dev
      - libvte-2.91-dev
      - libxkbfile-dev
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr
      - -DWITH_TELEPATHY=off
      - -DSNAP_BUILD=on

      # XXX: This is an hack to have a kind of bind-mount with absolute prefix.
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr

    override-build: |
      snapcraftctl build
      cp -av $SNAPCRAFT_PART_INSTALL/../src/snap/gui $SNAPCRAFT_STAGE/../snap

    organize:
      snap/remmina/current: .
    stage:
      - -./usr/share/fonts/**

    after:
      - libssh-0.8
      - freerdp
      - desktop-gtk3

  # Removing files that are accessible thanks to desktop plug
  desktop-gtk3:
    stage-packages:
      - gnome-icon-theme
      - libappindicator3-1
    stage:
      - -./usr/share/fonts/**
    override-build: |
      set -x
      snapcraftctl build
      export XDG_DATA_DIRS=$SNAPCRAFT_PART_INSTALL/usr/share
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache-3.0 -q $dir
        fi
      done

apps:
  remmina:
    # desktop-launch seems to be broken when setting up wayland env
    # so we disable it
    environment:
      DISABLE_WAYLAND: 1
    command: desktop-launch remmina
    common-id: org.remmina.Remmina.desktop
    desktop: usr/share/applications/org.remmina.Remmina.desktop
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - pulseaudio
      - unity7
      - password-manager-service
      - wayland

  winpr-makecert:
    command: winpr-makecert

  winpr-hash:
    command: winpr-hash

slots:
  remmina-gapp:
    interface: dbus
    bus: session
    name: org.remmina.Remmina
